name: Update-Copyright-Year

on:
  schedule:
    - cron: '0 3 1 1 *'
  workflow_dispatch:

jobs:
  Update-Copyright-Year:
    runs-on: ubuntu-latest
    steps:

      - name: Get current year
        id: date
        run: echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Update Copyright
        run: sed -i -E 's/(Copyright \(c\) ).+( meisnate12)/\1${{ steps.date.outputs.year }}\2/' LICENSE

      - name: Check Diff
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update at ${{ steps.date.outputs.date }} UTC" -a
          git push origin master

      - name: Discord Failure Notification
        uses: meisnate12/discord-notifications@master
        if: failure()
        with:
          webhook_id: ${{ secrets.BUILD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.BUILD_WEBHOOK_TOKEN }}
          message: <@&1079153184007790652>
          title: "Anime IDs Copyright: **Failure**"
          color: 16106776
          url: https://github.com/Kometa-Team/Anime-IDs/actions/runs/${{ github.run_id }}
          username: Metabot
          avatar_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/logo.png
          author: IMDb Awards
          author_icon_url: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/.github/git.png